# Массивы numpy

Примеры работы со списками, массивами, циклами в python3

In [3]:
from math import sqrt

r = [ 1.0, 1.5, -2.2 ]

length = sqrt( r[0]**2 + r[1]**2 + r[2]**2 )

print(length)

2.8442925306655784


In [4]:
r = [ 1.0, 1.5, -2.2 ]

avg = sum(r)/len(r)

print(avg)

0.09999999999999994


In [5]:
from math import *

r = [ 1.0, 1.5, 2.2 ]

logr = list(map(log,r))

print(logr)

r.append(1)

r.pop(2)

print(r)

[0.0, 0.4054651081081644, 0.7884573603642703]
[1.0, 1.5, 1]


In [8]:
from numpy import zeros

a = zeros(4,float)

print(a)

m = zeros([3,4,5,1],float)

print(m)

[0. 0. 0. 0.]
[[[[0.]
   [0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]
   [0.]]]]


In [ ]:
from numpy import loadtxt

a = loadtxt("values.txt",float)

print(a)

In [9]:
from numpy import array

a = array([1,2,3,4],int)

b = 2*a

print(a)
print(b)

print(a*b)

[1 2 3 4]
[2 4 6 8]
[ 2  8 18 32]


In [10]:
from numpy import array,dot

a = array([1,2,3,4],int)

b = array([2,4,6,8],int)

print(a*b)

print(dot(a,b))

[ 2  8 18 32]
60


In [12]:
from numpy import array,dot

a = array([[1,3],[2,4]],int)

b = array([[4,-2],[-3,1]],int)

c = array([[1,2],[2,1]],int)

print(dot(a,b)+2*c)

[[-3  5]
 [ 0  2]]


In [13]:
from math import sqrt
from numpy import array

a = array([[1,2,3],[4,5,6]],float)

b = list(map(sqrt,a))

print(b)

print(a.size)

print(a.shape)

TypeError: only size-1 arrays can be converted to Python scalars

In [15]:
from numpy import loadtxt, array

from math import log,exp

# load data and calculate average

values = loadtxt("values.txt",float)

mean = sum(values)/len(values)

print(mean)

#calculate mean square

mean_square = sum(values*values)/len(values)

print(mean_square)

# calculate geometric mean

logs = array(map(log,values),float)

geometric = exp(sum(logs)/len(logs))

print(geometric)

OSError: values.txt not found.

In [16]:
from numpy import loadtxt,log

from math import exp

values = loadtxt("values.txt",float)

geometric = exp(sum(log(values))/len(values))

print(geometric)

OSError: values.txt not found.

In [17]:
r = [ 1, 3, 5, 7, 9, 11, 13, 15 ]

s = r[:]

r[0] = 2

print(r)

print(s)

[2, 3, 5, 7, 9, 11, 13, 15]
[1, 3, 5, 7, 9, 11, 13, 15]


In [18]:
r = [ 1, 3, 5 ]

for n in r:

    print(n)
    print(2*n)

print("Finished")

1
2
3
6
5
10
Finished


In [ ]:
r = range(5)

for n in r:
    
    print("Hello again")
    
for n in r:
    
    print(n**2)